apiVersion: v1
kind: Service
metadata:
  name: open-relationship-cms
spec:
  selector:
    app: open-relationship-cms
    tier: backend
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: open-relationship-cms
    tier: backend
  name: open-relationship-cms
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: open-relationship-cms
        tier: backend
    spec:
      containers:
      - image: gcr.io/mirrormedia-1470651750304/open-relationship:dev_liyibass_57_cms
        # imagePullPolicy: IfNotPresent
        name: open-relationship-cms
        ports:
        - containerPort: 3000
          protocol: TCP
      terminationGracePeriodSeconds: 30
  minReadySeconds: 20
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
    type: RollingUpdate
